// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account": {
            "get": {
                "description": "role admin: get all account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "get all account",
                "responses": {
                    "200": {
                        "description": "Get all account successful",
                        "schema": {
                            "$ref": "#/definitions/common.success_response"
                        }
                    },
                    "400": {
                        "description": "Get all account failure",
                        "schema": {
                            "$ref": "#/definitions/common.error_response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create new account with user's info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "register new account",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.Account_Register"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created new account successfully",
                        "schema": {
                            "$ref": "#/definitions/common.success_response"
                        }
                    },
                    "400": {
                        "description": "Create failure",
                        "schema": {
                            "$ref": "#/definitions/common.error_response"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Log in to the account with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "login to account",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.RequestLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful login",
                        "schema": {
                            "$ref": "#/definitions/common.success_response"
                        }
                    },
                    "400": {
                        "description": "login failure",
                        "schema": {
                            "$ref": "#/definitions/common.error_response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Account_Register": {
            "type": "object",
            "properties": {
                "account_role": {
                    "enum": [
                        "HR",
                        "ADMIN"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/account.EnumAccountRole"
                        }
                    ]
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "account.EnumAccountRole": {
            "type": "string",
            "enum": [
                "HR",
                "ADMIN"
            ],
            "x-enum-varnames": [
                "HR",
                "ADMIN"
            ]
        },
        "account.RequestLogin": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "common.error_response": {
            "type": "object",
            "properties": {
                "log": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status-code": {
                    "type": "integer"
                }
            }
        },
        "common.success_response": {
            "type": "object",
            "properties": {
                "data": {},
                "filter": {},
                "message": {
                    "type": "string"
                },
                "paging": {},
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Human Resources Management System",
	Description:      "Human Resource Management (HRM)\nServer is a comprehensive software or hardware system designed to manage all aspects of personnel-related activities within an organization.\nIt encompasses employee information management, timekeeping, payroll, training and development, performance management, document management, employee interaction, security, compliance.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
