definitions:
  account.Account_Register:
    properties:
      account_role:
        allOf:
        - $ref: '#/definitions/account.EnumAccountRole'
        enum:
        - HR
        - ADMIN
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  account.AccountFilter:
    properties:
      account_role:
        enum:
        - HR
        - ADMIN
        type: string
      created_time_from:
        type: string
      created_time_to:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
  account.EnumAccountRole:
    enum:
    - HR
    - ADMIN
    type: string
    x-enum-varnames:
    - HR
    - ADMIN
  account.RequestLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  common.error_response:
    properties:
      log:
        type: string
      message:
        type: string
      status-code:
        type: integer
    type: object
  common.success_response:
    properties:
      data: {}
      filter: {}
      message:
        type: string
      paging: {}
      status:
        type: integer
    type: object
  oauth.TokenResponse:
    properties:
      access_token:
        type: string
      expiry:
        type: string
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Human Resource Management (HRM)
    Server is a comprehensive software or hardware system designed to manage all aspects of personnel-related activities within an organization.
    It encompasses employee information management, timekeeping, payroll, training and development, performance management, document management, employee interaction, security, compliance.
  title: Human Resources Management System
  version: "1.0"
paths:
  /api/v1/account/get-all:
    post:
      consumes:
      - application/json
      description: Get all accounts. Requires admin role.
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Total number of items per page
        in: query
        name: total
        type: integer
      - description: Get all accounts request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.AccountFilter'
      produces:
      - application/json
      responses:
        "200":
          description: Get all accounts successful
          schema:
            $ref: '#/definitions/common.success_response'
        "400":
          description: Get all accounts failure
          schema:
            $ref: '#/definitions/common.error_response'
      security:
      - ApiKeyAuth: []
      summary: Get all accounts
      tags:
      - Account
  /api/v1/account/register:
    post:
      consumes:
      - application/json
      description: create new account with user's info
      parameters:
      - description: Register request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.Account_Register'
      produces:
      - application/json
      responses:
        "201":
          description: Created new account successfully
          schema:
            $ref: '#/definitions/common.success_response'
        "400":
          description: Create failure
          schema:
            $ref: '#/definitions/common.error_response'
      security:
      - ApiKeyAuth: []
      summary: register new account
      tags:
      - Account
  /api/v1/auth/login-google-account:
    post:
      description: Get user information from Google using OAuth2 token
      parameters:
      - description: OAuth2 token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/oauth.TokenResponse'
      produces:
      - application/json
      responses:
        "200":
          description: User information retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/common.success_response'
            - properties:
                data:
                  additionalProperties: true
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.error_response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.error_response'
      summary: Get user information from Google
      tags:
      - Auth
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Log in to the account with email and password
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/account.RequestLogin'
      produces:
      - application/json
      responses:
        "200":
          description: Successful login
          schema:
            $ref: '#/definitions/common.success_response'
        "400":
          description: login failure
          schema:
            $ref: '#/definitions/common.error_response'
      summary: login to account
      tags:
      - Account
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
